### ISSUE TITLE
[QUESTION] About the map size

### ISSUE THREAD

**Issue by franfdezmorales** [supernovaplus/ttmap#1]
Hey man, im trying to replicate this map into my server but im having few problems, i dont find any map tiles likes your, could you give some info on how can i generate? Ty in advance!

**Comment by jonraka** [comment]
I used photoshop with a slice tool, then changed up the names with a [script](https://github.com/supernovaplus/ttmap/blob/master/_tools/rename_tiles.js)
I recently made aware of a tool called [Maptiler](https://www.maptiler.com/desktop/) which makes this much easier, however it costs money have tiles without a watermark.
Also keep in mind that if map size changes you will have to shift around the [CSR transformation options](https://github.com/supernovaplus/ttmap/blob/c55786dc11cf05c8b2941c60827b8a0ee8c1400e/src/js/main.js#L76)

**Comment by supernovaplus** [comment]
I used photoshop with a slice tool, then changed up the names with a [script](https://github.com/supernovaplus/ttmap/blob/master/_tools/rename_tiles.js)
I recently made aware of a tool called [Maptiler](https://www.maptiler.com/desktop/) which makes this much easier, however it costs money have tiles without a watermark.
Also keep in mind that if map size changes you will have to shift around the [CSR transformation options](https://github.com/supernovaplus/ttmap/blob/c55786dc11cf05c8b2941c60827b8a0ee8c1400e/src/js/main.js#L76)

**Comment by franfdezmorales** [comment]
Ty for the fast response, could you give ur map size? Really appreciated!

**Comment by franfdezmorales** [comment]
Okey, nevermind, i got the resolution, 4068 x 4068, one more time, ty for ur fast response!

**Comment by jonraka** [comment]
9216x9216 for 7th zoom, then it gets divided by 2 for each lower zoom level
tile size 288px

**Comment by supernovaplus** [comment]
9216x9216 for 7th zoom, then it gets divided by 2 for each lower zoom level
tile size 288px

**Comment by franfdezmorales** [comment]
Probably need to do some questions, could you give me some discord or any contact method? I can create other issue but i dont think could be a good idea :S

**Comment by JustinRijsdijk** [comment]
Hey, do you perhaps have a link to the Photoshop tool that you have used for generating your tiles?

**Comment by franfdezmorales** [comment]
Hey, you can do with native photoshop, i didnt remember where was the function but was native photoshop, i didnt install any plugin.

**Comment by supernovaplus** [comment]
I used the built in slice tool
![image](https://user-images.githubusercontent.com/13980602/165753758-884849c3-ed36-419a-af04-ee73c5ee6c25.png)
Select the whole canvas with the slice tool, then select to divde
![image](https://user-images.githubusercontent.com/13980602/165753778-e12de682-0de1-4645-9d02-9bdad1681fdb.png)
![image](https://user-images.githubusercontent.com/13980602/165753785-77855c1c-d013-4680-a76c-b3eea0ece821.png)
Save it by File > Export > Save for Web (legacy)

**Comment by JustinRijsdijk** [comment]
and then you set the Pixels Per Slice to the amount of pixels defined in the [Image Rename Tool](https://github.com/supernovaplus/ttmap/blob/master/_tools/rename_tiles.js)?

**Comment by JustinRijsdijk** [comment]
And how did you handle the zoom levels?

**Comment by supernovaplus** [comment]
> And how did you handle the zoom levels?

Each zoom levels halfs the resolution, I started with zoom level 7, my resolution was 9216x9216 with each tile being 288, then 6th zoom level goes 4608x4608, 5th level 2304x2304 etc. until I end up with single tile with 288 resolution
Each tile resolution stays the same.
![image](https://user-images.githubusercontent.com/13980602/166156806-4d3b0b32-7f88-45b6-9167-886fe07e690a.png)

**Comment by JustinRijsdijk** [comment]
> > And how did you handle the zoom levels?
> 
> Each zoom levels halfs the resolution, I started with zoom level 7, my resolution was 9216x9216 with each tile being 288, then 6th zoom level goes 4608x4608, 5th level 2304x2304 etc. until I end up with single tile with 288 resolution Each tile resolution stays the same. ![image](https://user-images.githubusercontent.com/13980602/166156806-4d3b0b32-7f88-45b6-9167-886fe07e690a.png)

Thanks, we figured it out ourselves litterally 5 minutes ago haha. Thanks for you help!

**Comment by casperiv0** [comment]
> Also keep in mind that if map size changes you will have to shift around the [CSR transformation options](https://github.com/supernovaplus/ttmap/blob/c55786dc11cf05c8b2941c60827b8a0ee8c1400e/src/js/main.js#L76)

@supernovaplus, sorry for the ping, however, I've been struggling to understand this topic and I'm trying to improve the positioning calculations I have. How did you calculate all the values defined for your CRS Transformation? Thankyou!

**Comment by supernovaplus** [comment]
> > Also keep in mind that if map size changes you will have to shift around the [CSR transformation options](https://github.com/supernovaplus/ttmap/blob/c55786dc11cf05c8b2941c60827b8a0ee8c1400e/src/js/main.js#L76)
> 
> @supernovaplus, sorry for the ping, however, I've been struggling to understand this topic and I'm trying to improve the positioning calculations I have. How did you calculate all the values defined for your CRS Transformation? Thankyou!

I haven't done any calculations. What I did is I placed markers and poly lines of known locations on correct coordinates then manually lined up the map to the markers. Trial and error.

**Comment by casperiv0** [comment]
> I haven't done any calculations. What I did is I placed markers and poly lines of known locations on correct coordinates then manually lined up the map to the markers. Trial and error.

Ah fair enough. Any places you'd recommend that are quite easy to line up?

**Comment by supernovaplus** [comment]
> Ah fair enough. Any places you'd recommend that are quite easy to line up?

I start with 0,0, which is in vinewood, then I mark some edges of the buildings, small buildings, piers, end of the roads, and small islands

https://gta-5-map.com have copy map location when you right click, where you can get x and y coordinates, so you could use that for markers.

![Untitle34344](https://github.com/supernovaplus/ttmap/assets/13980602/2e0dcd39-97cf-47fc-9871-adc766ea3510)

**Comment by samuelcardillo** [comment]
Kinda reopening this in 2024 but any chances to get a tutorial on how to export a map properly ? I really suck at Photoshop. I think I got the hang of it but I am still having some issues.

**Comment by supernovaplus** [comment]
Currently I'm testing out the npm sharp package, it has tiling ability which might make this much easier
https://www.npmjs.com/package/sharp
https://sharp.pixelplumbing.com/api-output#tile
