### ISSUE TITLE
[Question] Backend / Resource

### ISSUE THREAD

**Issue by JustinRijsdijk** [supernovaplus/ttmap#2]
Hello, 
after your amazing help in the other issue, we have managed to get our own map working.
Only now we ofcourse want to implement this into our own server.
I saw your other repo: [tt-api-proxy](https://github.com/supernovaplus/tt-api-proxy-heroku).
Could you perhaps also supply us with the FiveM resource that you are accessing trough[https://tycoon-${server.endpoint}.users.cfx.re/status/map/positions2.json](https://tycoon-2epova.users.cfx.re/status/map/positions2.json)

**Comment by supernovaplus** [comment]
I didn't make the back end, I don't have the source code.
It was made by https://github.com/glitchdetector

**Comment by JustinRijsdijk** [comment]
> I didn't make the back end, I don't have the source code. It was made by https://github.com/glitchdetector

Thanks for your reply. I've sent him an email!

**Comment by supernovaplus** [comment]
I just looks at the credits, it might be this resource https://forum.cfx.re/t/release-livemap/49901 (https://github.com/TGRHavoc/live_map)
